language: python

services:
    - docker

before_install:
    - sudo apt-get update
    - sudo apt-get -y install docker-ce realpath
    - yes | docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS

install: true

script:
  - ./tests/bin/docker-tests.sh --image vac_man:testing
