language: python

services:
    - docker

before_install:
    - sudo apt-get update
    - sudo apt-get -y install docker-ce realpath
    - chmod +x tests/bin/docker-tests.sh

install: true

script:
  - ./tests/bin/docker-tests.sh
